<?php
//
//
//namespace App\form;
//
//
//use Symfony\Component\Form\AbstractType;
//use Symfony\Component\Form\Extension\Core\Type\TextareaType;
//use Symfony\Component\Form\Extension\Core\Type\TextType;
//use Symfony\Component\Form\FormBuilderInterface;
//use Symfony\Component\OptionsResolver\OptionsResolver;
//
//
//
//class ContactController extends AbstractType
//{
//    /**
//     * creation du formulaire
//     * @param FormBuilderInterface $builder
//     * @param array $options
//     */
//    public function buildForm(FormBuilderInterface $builder, array $options)
//    {
//       $builder
//           ->add('nom', TextType::class)
//           ->add('prenom', TextType::class)
//           ->add('email', TextType::class)
//           ->add('telephone', TextType::class)
//           ->add('message', TextareaType::class);
//    }
//
//    /**
//     * configurations des options
//     * @param OptionsResolver $resolver
//     */
//    public function configureOptions(OptionsResolver $resolver)
//    {
//        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
//    }
//
//    /**
//     * prefixer les balise
//     * @return string|null
//     */
//
//    public function getBlockPrefix()
//    {
//        return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
//    }
//
//}